### PR TITLE
Large Refactor

### PR DESCRIPTION
**Pull request by yofreke**
Some of this is done, some is still in progress.  We are using clmtrackr internally for a project, so we thought some of the changes might be appreciated upstream.
- Project built with webpack
- Examples are implemented with react (included generic `ui/container/TrackerContainer.js` for use in other projects)
- Publish using gh-pages tool
  - Check out the new examples here: https://jsio-private.github.io/clmtrackr/
- Move shader code in to shader files
- Integrated PRs: #45 #53 #83 #67 
- Source now compatible with other es6 / babel projects
- Fixed model JSONs (generated from model JS files using `npm run generateModelJsons`)
- Began linting project with eslint
- General cleanup of code
## Todo:
- [ ] Move missing examples from `gh-pages` in to react
- [ ] Move docs from `gh-pages` to react
- [ ] Figure out why newer models (found on `gh-pages`) cause tracker to lose face after ~1s
- [ ] Finish ES6ing + linting classes

### CODE REVIEW

**Comment by Skylion007** [comment]
Build script fails on Windows:  

Failed at the clmtrackr@0.0.1 build script 'NODE_ENV=production jsio-webpack'

Alas this is not proper syntax for environmental variables in Windows. :(

**Comment by jdaily** [comment]
It seem's this also fails when installing as an electron dependency `Node.js 6.5.0, Chromium 53.0.2785.143, and Electron 1.4.7`

**Comment by yofreke** [comment]
Hey guys, thanks for the interest! This was for a project at work, but we have shelved it for the time being.  I would be totally willing to collaborate on this some more in the future, but cannot spare the time right now.  It uses another internal project called jsio-webpack (which is just a webpack config helper) that sees regular backwards-incompatible updates, so I cannot even say for certain that it would build on a posix box right now.  Probably just some minor tweaks, but I have no idea.

We will definitely keep this PR updated if we have the time to come back and work on this some more!

**Comment by auduno** [comment]
Hi! Thanks very much for the PR! Parts of this PR has now been manually merged into master with [this commit](https://github.com/auduno/clmtrackr/commit/da28f93befa7709110ec7a68e03efbd1feee24e9). Github does not manage to resolve that to this pull request, so I'll have to close this manually.

**Pull request closed without merging**
